version: '3.9'

services:
  php:
    build: 
      context: ./.docker/php
      dockerfile: php.dockerfile
    container_name: php
    networks:
      - app

    
  postgres:
    image: postgres:16.4
    restart: unless-stopped
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    networks:
      - app

  nginx: 
    build:
      context: ./.docker/nginx
      dockerfile: nginx.dockerfile
    restart: unless-stopped
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - app
networks:
  app:
    driver: bridge
    
